server:
  port: 8085
  context-path: /demo
spring:
  datasource:
    # 启动时自动运行的 SQL 文件
    schema: classpath:init-sql/schema.sql
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=UTF-8&utoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
